[build-system]
requires = [
    "setuptools>=77.0.3",
    "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "SeInE"
dynamic = ["version"]
description = "Selectivity Inference from Event counts using Hierarchical Bayesian inference"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
    { name = "Alexander Schmidt" }
]

dependencies = [
    "numpy",
    "scipy",
    "dynesty",
    "pathos",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["seine*"]

[tool.setuptools_scm]
version_file = "seine/_version.py"
local_scheme = "no-local-version"